In [31]:
import numpy as np

#sigmoid and its derivative
def sigmoid(t):
    return 1 / (1 + np.exp(-t))
    
def sigmoid_derivative(p):
    return p * (1 - p)

np.random.seed(100)


class NeuralNetwork:
    def __init__(self,x=[[]],y=[],numLayers=2,numNodes=2,eta=0.1,maxIter=10000):
        self.x = x
        self.y = y
        
        self.lr = eta
        self.numLayers = numLayers
        self.numNodes = numNodes
        
        self.weights = [np.random.uniform(-1,1,(self.x.shape[1],numNodes))] #create the weights from the inputs to the first layer
        
        for i in range(1,numLayers-1):
            self.weights.append(np.random.uniform(-1,1,(numNodes,numNodes))) #create the random weights between internal layers
            
        self.weights.append(np.random.uniform(-1,1,(numNodes,1))) #create weights from final layer to output node
#         print(self.weights[-1])
        
        self.outputs = np.zeros(self.y.shape)    #creates an output array of similar size to y 
        
        self.bias = [np.ones(numNodes)] #create bias nodes to the first layer, all 1's
        for i in range(numLayers-1):    #create bias in btwn hidden layers
            self.bias.append(np.ones(numNodes))
        self.bias.append(np.ones(self.y.shape))#create bias node to last layer, to output, all 1's        
        
        self.train(learningRate=eta,maxIterations=maxIter) 

    def train(self,learningRate,maxIterations):       
        for i in range(1,maxIterations):
            self.feedforward()
            self.backprop()

    def predict(self,x=[]):
        test.feedforward()
        return self.outputs


    def feedforward(self):
        self.layerdata = []
        
        #this adds in the input layer to the first hidden layer
        self.to_first_layer = sigmoid(np.dot(self.x, self.weights[0]) + self.bias[0])
        self.layerdata.append(self.to_first_layer) #
        
        #this adds from hidden layer to hidden layer
        for i in range(1,self.numLayers-1):
            self.layerdata.append(sigmoid(np.dot(self.layerdata[i-1], self.weights[i] + self.bias[i])))          
            
        #this adds from the last hidden layer to output
#         print(self.layerdata[-1])
#         print(self.weights[-1])
        
        self.to_output_layer =  sigmoid(np.dot(self.layerdata[-1], self.weights[-1]) + self.bias[-1])
        self.layerdata.append(self.to_output_layer) 
        self.outputs = (self.to_output_layer)
        
#         print(self.weights[-1])


    def backprop(self): 

        #error from the actual and predicted output
        self.error = (self.y - self.layerdata[-1])
        
        #update the weights to output
        self.output_layer_gradient = sigmoid_derivative(self.layerdata[-1])      
        self.hidden_delta = self.error * self.output_layer_gradient #output delta
        test = np.dot(self.to_first_layer.T, self.hidden_delta) * self.lr  
        print(test)
        print(self.weights[-1])
        self.weights[-1] = self.weights[-1] +  np.dot(self.to_first_layer.T, self.hidden_delta) * self.lr 
        
#         print(self.weights[-1])
        
        #loop the hidden layers  
        j = -1
        for i in range(1, self.numLayers-1,):
            self.hidden_layer_gradient = sigmoid_derivative(self.layerdata[j-1])    
            
            self.hidden_error = np.dot(self.hidden_delta,self.weights[j].T) 
            self.hidden_delta = self.hidden_error * self.hidden_layer_gradient
#             print(np.dot(self.layerdata[j-1].T, self.hidden_delta) * self.lr  )
            self.weights[j-1] = self.weights[j-1] +  np.dot(self.layerdata[j-1].T, self.hidden_delta) * self.lr  
            j = j-1
            
        #update the input's weights
        self.hidden_layer_gradient = sigmoid_derivative(self.to_first_layer)         
        self.hidden_error = np.dot(self.hidden_delta,self.weights[1].T)
        self.hidden_delta = self.hidden_error * self.hidden_layer_gradient
        self.weights[0] = self.weights[0] + np.dot(self.x.T, self.hidden_delta) * self.lr  

In [32]:
    def setUp(self):
        self.testOne = np.array([[0,1],[1,0],[0,0],[1,1]])
        self.outOne = np.array([1,0,1,0])
        
        self.outTwo = np.array([1,1,0,0])

In [33]:
testOne = np.array([[0,1],[1,0],[0,0],[1,1]])
outOne = np.array([1,0,1,0])

# print(outOne.shape)
test = NeuralNetwork(testOne, outOne, 3,3)

[[ 0.00419145 -0.0299958   0.00419145 -0.0299958 ]
 [ 0.00297297 -0.02132222  0.00297297 -0.02132222]
 [ 0.00330912 -0.02371463  0.00330912 -0.02371463]]
[[ 0.95724757]
 [ 0.6233663 ]
 [-0.65611797]]


ValueError: shapes (4,4) and (3,3) not aligned: 4 (dim 1) != 3 (dim 0)

In [14]:
    def test_eval_separable2(self):
        """Linearly separable data 2"""
        self.nn = NeuralNetwork(self.testOne,self.outOne,3,3)
        val = self.nn.predict(np.array([0,1]))
        self.assertTrue(val>.9)

In [15]:
    def test_eval_xor(self):
        """XOR data"""
        self.nn = NeuralNetwork(self.testOne,self.outTwo,3,3)
        val = self.nn.predict(np.array([0,0]))
        self.assertTrue(val<0.1)

In [16]:
    def test_eval_xor2(self):
        """XOR data2"""
        self.nn = NeuralNetwork(self.testOne,self.outTwo,3,3)
        val = self.nn.predict(np.array([0,1]))
        self.assertTrue(val>0.9)